server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
#  main:
#    allow-circular-references: true
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/uservideos
#    username: root
#    password: 287515GGgantic_

# logging
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

video:
  save-path: C:/Users/Tangs/Desktop/dd_uploads
  result-path: C:/Users/Tangs/Desktop/dd_results
  max-size: 1073741824 # 1G